FORMAT: 1A
HOST: http://deploy.cwp.govt.nz/api/

# silverstripe dashboard

This API is a newly developed interface for the CWP Dashbaord.

## Instances [/instances]

### List All Instances [GET]

Will return a list of all instances that you have the authority to view, with relevant datapoints.

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": "CWP001",
                    "name": "CWP Instance 001",
                    "primary_domain": "mom.govt.nz",
                    "agency": "Minstry of Magic",
                    "size": "large",
                    "disaster_recovery": "active",
                    "created": "02-07-2014",
                    "environments": {
                        "data": [
                            {
                                "name": "prod",
                                "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                                "deployer": "Albus Dumbledore",
                                "date": "24-01-2017"
                            },
                            {
                                "name": "uat",
                                "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                                "deployer": "Severus Snape",
                                "date": "23-01-2017"
                            }
                        ]
                    }
                },
                {
                    "id": "CWP002",
                    "name": "CWP Instance 002",
                    "primary_domain": "butsiriusly.govt.nz",
                    "agency": "Ministry of Magic",
                    "size": "small",
                    "disaster_recovery": "none",
                    "created": "07-07-2016",
                    "environments": {
                        "data": [
                            {
                                ...
                            }
                        ]
                    }
                }
            ]
        }

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }