FORMAT: 1A
HOST: http://deploy.cwp.govt.nz

# Deploynaut API

This API is a newly developed interface for the CWP Dashboard. Data structure is based on the
[JSON API specifications](http://jsonapi.org/).


# Using the API [/naut]

In order to use the API, you will need to acquire a token via Service Desk request. In order to authenticate,
you should use HTTP Basic Authentication, using your email with the API token.

Any request you make to an endpoint should include the following:

## Making a request: Headers [GET]

These headers will authenticate you against Deploynaut to evaluate whether you have the permissions necessary
to access the information you are requesting. You can send a GET request to deploy.cwp.govt.nz/naut/profile
to test that you are authenticating correctly - it will return your user information.

+ Request (application/json)

    + Headers

            X-api-version: 1.0
            Authorization: Basic c2hlcmJlcnQubGVtb25AaG9nd2FydHMudWs6ZmE4ODc4N2ZjZDk5Nzg3
            Accept: application/json
            Host: deploy.cwp.govt.nz


+ Response 200 (application/json)

        {
            "data": [
                {
                    "type": "users",
                    "id": "2379",
                    "name": "Albus Dumbledore",
                    "email": "sherbert.lemon@hogwarts.uk"
                }
            ]
        }



# Stacks [/naut]

## List all stacks [GET /naut]

Will return a list of all stacks that you have the authority to view, with relevant datapoints.

+ Response 200 (application/json)

        {
            "count": 1,
            "data": [
                {
                    "type": "stacks",
                    "name": "CWP001",
                    "title": "CWP Stack 001",
                    "created": "02-07-2014",
                    "environments": {
                        "count": 2,
                        "data": [
                            {
                                "type": "environments",
                                "name": "prod",
                                "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                                "deployer": {
                                    "location": "deploy.govt.nz/naut/users/2379"
                                },
                                "date": "24-01-2017"
                            },
                            {
                                "type": "environments",
                                "name": "uat",
                                "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                                "deployer": {
                                    "location": "deploy.govt.nz/naut/users/21279"
                                },
                                "date": "23-01-2017"
                            }
                        ]
                    }
                }
            ]
        }

## Get data about a stack [GET /naut/project/$name]

Get data about a specific stack

+ Response 200 (application/json)

        {
            "data": {
                "type": "stacks",
                "name": "CWP001",
                "title": "CWP Stack 001",
                "created": "02-07-2014",
                "environments": {
                    "count": 2,
                    "data": [
                        {
                            "type": "environments",
                            "name": "prod",
                            "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                            "deployer": {
                                "location": "deploy.govt.nz/naut/users/2379"
                            },
                            "date": "24-01-2017"
                        },
                        {
                            "type": "environments",
                            "name": "uat",
                            "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                            "deployer": {
                                "location": "deploy.govt.nz/naut/users/21279"
                            },
                            "date": "23-01-2017"
                        }
                    ]
                }
            }
        }

## List users [GET /naut/project/$name/team]

Returns a list of roles and users in those roles for a stack

+ Response 200 (application/json)

        {
            "data": [
                {
                    "type": "roles",
                    "name": "Stack Manager",
                    "users": {
                        "count": 2,
                        "data": [
                            {
                                "type": "users",
                                "id": "2379",
                                "name": "Albus Dumbledore",
                                "email": "sherbert.lemon@hogwarts.uk",
                            },
                            {
                                "type": "users",
                                "id": "21279",
                                "name": "Severus Snape",
                                "email": "halfbloodprince@hogwarts.uk",
                            }
                        ]
                    }
                },
                {
                    "type": "roles",
                    "name": "Deployment Manager",
                    "users": {
                        "count": 1,
                        "data": [
                            {
                                "type": "users",
                                "id": "224",
                                "name": "Minerva McGonagall",
                                "email": "mcgryffindor@hogwarts.uk",
                            }
                        ]
                    }
                }
            ]
        }


# Snapshots [/snapshots]

## List all snapshots [GET /naut/project/$name/snapshots]

Returns a list of snapshots associated with a stack

+ Response 200 (application/json)

        {
            "count": 1,
            "data": [
                {
                    "type": "snapshots",
                    "id": "398433",
                    "created": "25-01-2017",
                    "author": {
                        "data": [
                            {
                                "type": "users",
                                "id": "2379",
                                "name": "Albus Dumbledore",
                                "email": "sherbert.lemon@hogwarts.uk",
                            }
                        ]
                    },
                    "source": {
                        "data": [
                            {
                                "type": "environments",
                                "name": "prod"
                            }
                        ]
                    },
                    "owner":  {
                        "data": [
                            {
                                "type": "environments",
                                "name": "uat"
                            }
                        ]
                    },
                    "mode": "db",
                    "size": "2096",
                    "download_link": "deploy.cwp.govt.nz/path/to/snapshot.sspak"
                }
            ]
        }

## Create a snapshot [POST /naut/project/$name/snapshots]

Create a snapshot of an environment associated with a stack. The response immediately returned will
contain a `location`, which will return a HTTP 204 response until the snapshot has completed. At that
point, the response will change to HTTP 200, and the download link will be returned.

+ Parameters

    + environment: prod (string)
    + mode: db|assets|all (string)

+ Request (application/json)

    + Body

            {
                "environment": "prod",
                "mode": "all",
            }


+ Response 202 (application/json)

        {
            "location": "deploy.cwp.govt.nz/naut/project/CWP001/snapshots/23",
            "data": [
                {
                    "type": "snapshots",
                    "id": "23",
                    "created": "25-01-2017",
                    "author": {
                        "data": [
                            {
                                "type": "users",
                                "id": "2379",
                                "name": "Albus Dumbledore",
                                "email": "sherbert.lemon@hogwarts.uk",
                            }
                        ]
                    },
                    "source": {
                        "data": [
                            {
                                "type": "environments",
                                "name": "prod"
                            }
                        ]
                    },
                    "owner":  {
                        "data": [
                            {
                                "type": "environments",
                                "name": "prod"
                            }
                        ]
                    },
                    "mode": "all"
                }
            ]
        }

## Get snapshot status [GET /naut/project/$name/snapshots/$id]

You should poll this URL (returned from the CREATE SNAPSHOT method) to receive updates on the status of
the snapshot. If the snapshot is incomplete, the response will be HTTP 204 (NO CONTENT); otherwise an
HTTP 200 response will be returned, with a `download_link` from which you can download the `.sspak` file.

+ Response 204

+ Response 200 (application/json)

        {
            "data": [
                {
                    "type": "snapshots",
                    "id": "23",
                    "created": "25-01-2017",
                    "author": {
                        "data": [
                            {
                                "type": "users",
                                "id": "2379",
                                "name": "Albus Dumbledore",
                                "email": "sherbert.lemon@hogwarts.uk",
                            }
                        ]
                    },
                    "source": {
                        "data": [
                            {
                                "type": "environments",
                                "name": "prod"
                            }
                        ]
                    },
                    "owner":  {
                        "data": [
                            {
                                "type": "environments",
                                "name": "prod"
                            }
                        ]
                    },
                    "mode": "all",
                    "size": "3339820989",
                    "download_link": "www.deploy.cwp.govt.nz/path/to/snapshot.sspak"
                }
            ]
        }

## Delete a snapshot [DELETE /naut/project/$name/snapshots/$id]

This URL will delete the snapshot from the database. Please be careful with this, as reversing the operation
is expensive and difficult.

+ Response 204
