FORMAT: 1A
HOST: http://deploy.cwp.govt.nz/naut

# Deploynaut API

This API is a newly developed interface for the CWP Dashboard. Data structure is based on the 
[JSON API specifications](http://jsonapi.org/).


# Using the API [/]

In order to use the API, you will need to acquire a token via Service Desk request. Any request you make to
an endpoint should include the following:

## Making a request: Headers [GET]

+ Request (application/json)

    + Headers
    
            X-api-version: 1.0
            X-user-id: 1242
            X-user-token: fa88787fcd99787
            Accept: application/json
            Host: deploy.cwp.govt.nz

+ Response 200 (application/json)

        {
            "data": [
                {
                    "type": "users",
                    "id": "2379",
                    "name": "Albus Dumbledore",
                    "email": "sherbert.lemon@hogwarts.uk",
                    "phone": "0203040506"
                }
            ]
        }

## Authentication Tokens [/tokens]

You will require 

## Instances [/projects]

### List all instances [GET /projects]

Will return a list of all instances that you have the authority to view, with relevant datapoints.

+ Response 200 (application/json)

        {
            "count": 1,
            "data": [
                {
                    "type": "instances",
                    "id": "CWP001",
                    "name": "CWP Instance 001",
                    "primary_domain": "mom.govt.nz",
                    "agency": "Ministry of Magic",
                    "size": "large",
                    "disaster_recovery": "active",
                    "created": "02-07-2014",
                    "environments": {
                        "count": 2,
                        "data": [
                            {
                                "type": "environments",
                                "id": "1",
                                "name": "prod",
                                "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                                "deployer": {
                                    "data": [
                                        {
                                            "type": "users",
                                            "id": "2379",
                                            "name": "Albus Dumbledore",
                                            "email": "sherbert.lemon@hogwarts.uk",
                                            "phone": "0203040506"
                                        }
                                    ]
                                },
                                "date": "24-01-2017"
                            },
                            {
                                "type": "environments",
                                "id": "2",
                                "name": "uat",
                                "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                                "deployer": {
                                    "data": [
                                        {
                                            "type": "users",
                                            "id": "21279",
                                            "name": "Severus Snape",
                                            "email": "halfbloodprince@hogwarts.uk",
                                            "phone": "020666666"
                                        }
                                    ]
                                },
                                "date": "23-01-2017"
                            }
                        ]
                    }
                }
            ]
        }

### Get data about an instance [GET /project/$name]

Get data about a specific instance

+ Response 200 (application/json)

        {
            "count": 1,
            "data": {
                "type": "instances",
                "id": "CWP001",
                "name": "CWP Instance 001",
                "primary_domain": "mom.govt.nz",
                "agency": "Minstry of Magic",
                "size": "large",
                "disaster_recovery": "active",
                "created": "02-07-2014",
                "environments": {
                    "count": 2,
                    "data": [
                        {
                            "type": "environments",
                            "id": "1",
                            "name": "prod",
                            "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                            "deployer": {
                                "data": [
                                    {
                                        "type": "users",
                                        "id": "2379",
                                        "name": "Albus Dumbledore",
                                        "email": "sherbert.lemon@hogwarts.uk",
                                        "phone": "0203040506"
                                    }
                                ]
                            },
                            "date": "24-01-2017"
                        },
                        {
                            "type": "environments",
                            "id": "2",
                            "name": "uat",
                            "build_sha": "d0bcf80381579a529957d77a6b0a69303afebe7e",
                            "deployer": {
                                "data": [
                                    {
                                        "type": "users",
                                        "id": "21279",
                                        "name": "Severus Snape",
                                        "email": "halfbloodprince@hogwarts.uk",
                                        "phone": "020666666"
                                    }
                                ]
                            },
                            "date": "23-01-2017"
                        }
                    ]
                }
            }
        }
        
### List users associated with an instance [GET /project/$id/users]

Returns a list of roles and users in those roles for an instance

+ Response 200 (application/json)

        {
            "data": [
                {
                    "type": "roles",
                    "id": "21",
                    "name": "Instance Manager",
                    "users": {
                        "count": 2,
                        "data": [
                            {
                                "type": "users",
                                "id": "2379",
                                "name": "Albus Dumbledore",
                                "email": "sherbert.lemon@hogwarts.uk",
                                "phone": "0203040506"
                            },
                            {
                                "type": "users",
                                "id": "21279",
                                "name": "Severus Snape",
                                "email": "halfbloodprince@hogwarts.uk",
                                "phone": "020666666"
                            }
                        ]
                    }
                },
                {
                    "type": "roles",
                    "id": "22",
                    "name": "Deployment Manager",
                    "users": {
                        "count": 1,
                        "data": [
                            {
                                "type": "users",
                                "id": "224",
                                "name": "Minerva McGonagall",
                                "email": "mcgryffindor@hogwarts.uk",
                                "phone": "02358222506"
                            }
                        ]
                    }
                }
            ]
        }
        
        
## Snapshots [/snapshots]

### List all snapshots for an instance [GET /project/$name/snapshots]

Returns a list of snapshots associated with an instance

+ Response 200 (application/json)

        {
            "count": 1,
            "data": [
                {
                    "type": "snapshots",
                    "id": "398433",
                    "created": "25-01-2017",
                    "author": {
                        "data": [
                            {
                                "type": "users",
                                "id": "2379",
                                "name": "Albus Dumbledore",
                                "email": "sherbert.lemon@hogwarts.uk",
                                "phone": "0203040506"
                            }
                        ]
                    },
                    "source": {
                        "data": [
                            {
                                "type": "environments",
                                "id": "1",
                                "name": "prod"
                            }
                        ]
                    },
                    "owner":  {
                        "data": [
                            {
                                "type": "environments",
                                "id": "2",
                                "name": "uat"
                            }
                        ]
                    },
                    "mode": "db",
                    "size": "2096"
                }
            ]
        }